# Generated by Django 2.2.11 on 2021-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='describ',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
